language: php
php:
  - "7.2"
  - "7.3"
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
    - PHAN_DISABLE_XDEBUG_WARN=1
before_install:
  - pecl install ast
install:
  - composer install
  - composer validate
script:
  - composer create-project phan/phan=1.2.5 ~/phan-install; ~/phan-install/phan
  - composer test
